name: pytrx37
channels:
  - defaults
  - conda-forge
dependencies:
  - gdal>=2.3
  - glob2
  - matplotlib
  - numpy
  - opencv>=3.4
  - pillow
  - pip
  - scipy>=1.3.0
  - pip:
    - osgeo
    - pytrx
